[workspace]
value_file = "signac_statepoint.json"

[default.action]
command = "python actions.py --action $ACTION_NAME {directories}"

[[action]]
name = "ligand_param"
products = ["ligparam/ligparam.json"]
resources.walltime.per_directory = "00:00:05"
group.maximum_size = 50

[[action]]
name = "docking"
previous_actions = ["ligand_param"]
products = ["dock/dock.json"]
resources.walltime.per_directory = "00:00:05"
group.maximum_size = 50

[[action]]
name = "md"
previous_actions = ["docking"]
products = ["md/md.json"]
resources.walltime.per_directory = "00:00:05"
group.maximum_size = 10

[[action]]
name = "gbsa"
previous_actions = ["md"]
products = ["gbsa/gbsa.json"]
resources.walltime.per_directory = "00:00:05"
group.maximum_size = 50

[[action]]
name = "metrics"
previous_actions = ["gbsa"]
products = ["metrics/metrics.json"]
resources.walltime.per_directory = "00:00:05"
group.maximum_size = 50
